name: benta
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_verification_code: ^1.1.7
  go_router: ^14.8.1
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  introduction_screen: ^3.1.17
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
